### ISSUE TITLE
Socket message handler error: TypeError: Cannot set property '1' of undefined

### ISSUE THREAD

**Issue by babsonmatt** [OpenRTMFP/ArcusNode#5]
```
error [Tue Sep 20 2011 05:02:01 GMT+0000 (UTC)]  Socket message handler error: TypeError: Cannot set property '1' of undefined
at /home/matt/arcus/ArcusNode/lib/arcus_node.js:534:30
at /home/matt/arcus/ArcusNode/lib/arcus_node.js:245:7
at Socket.<anonymous> (/home/matt/arcus/ArcusNode/lib/arcus_node.js:867:9)
at Socket.emit (events.js:70:17)
at UDP.onMessage [as onmessage] (dgram_uv.js:307:10)
02 58 65 0C 02 F4 8D 40 5F 4A B4 10 00 2D 80 03 .Xe....._J...-..
01 01 05 00 54 43 04 02 00 11 09 D0 D6 73 00 02 ....TC.......s..
00 04 70 6C 61 79 00 00 00 00 00 00 00 00 00 05 ..play..........
02 00 08 6D 79 73 74 72 65 61 6D FF FF FF FF FF ...mystream.....
FF FF FF FF                                     ....
```

**Comment by JanisGruzis** [comment]
How does one do that? Im quite new with flash and found rtmfp example with NetStream from following link: http://old.haxe.org/doc/flash/peer2peer
